import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/global.css";
import Header from "@/app/ui/common/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Quick Fun",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <Header />
      <div className="flex-grow p-6 md:overflow-y-auto md:p-12">{children}</div>
    </>
  );
}
