import type { Metadata } from "next";
import "@/styles/global.css";
import Header from "@/app/ui/common/Header";
import localFont from "next/font/local";

export const metadata: Metadata = {
  title: "Quick Fun",
  description: "Generated by create next app",
};

// Font files can be colocated inside of `app`
const SpoqaHanSansNeo = localFont({
  src: [
    {
      path: "../../public/font/SpoqaHanSansNeo-Light.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/font/SpoqaHanSansNeo-Medium.ttf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../../public/font/SpoqaHanSansNeo-Bold.ttf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--custom-font",
  display: "swap",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={SpoqaHanSansNeo.variable}>
      <body>
        <Header />
        <div className="flex-grow p-6 md:overflow-y-auto md:p-12">
          {children}
        </div>
      </body>
    </html>
  );
}
